memo/urls.py
from django.urls import path
from . import views

app_name = 'memo'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add_memo, name='add_memo'),
    path('detail/<int:memo_id>/', views.detail, name='detail'),
    path('del/<int:memo_id>/', views.del_memo, name='del_memo'),
    path('mod/<int:memo_id>/', views.mod_memo, name='mod_memo'),
]

mymemo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('memo.urls')),
]

memo/models.py
from django.db import models


class Memo(models.Model):
    title = models.CharField(max_length=150)        # default: blank=False, null=False
    text = models.TextField(blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

memo/forms.py
from django.forms import ModelForm
from .models import Memo


class MemoForm(ModelForm):
    class Meta:
        model = Memo
        fields = ['title', 'text']

memo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Memo
from .forms import MemoForm
from django.views.decorators.http import require_POST


def index(request):
    """メモ一覧"""
    memos = Memo.objects.all().order_by('created_date')
    return render(request, 'memo/index.html', {'memos': memos})


def detail(request, memo_id):
    """メモ詳細"""
    memo = get_object_or_404(Memo, id=memo_id)
    return render(request, 'memo/detail.html', {'memo': memo})


def add_memo(request):
    """メモ追加"""
    if request.method == "POST":
        form = MemoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('memo:index')
    else:
        form = MemoForm
    return render(request, 'memo/add_memo.html', {'form': form })


@require_POST # request.method=GET の時は実行されない
def del_memo(request, memo_id):
    """メモ削除"""
    memo = get_object_or_404(Memo, id=memo_id)
    memo.delete()
    return redirect('memo:index')


def mod_memo(request, memo_id):
    """メモ編集"""
    memo = get_object_or_404(Memo, id=memo_id)
    if request.method == "POST":
        form = MemoForm(request.POST, instance=memo)
        if form.is_valid():
            form.save()
            return redirect('memo:index')
    else:
        form = MemoForm(instance=memo)
    return render(request, 'memo/mod_memo.html', {'form': form, 'memo': memo})

memo/templates/memo/add_memo.html
{% extends 'memo/base.html' %}

{% block content %}

  <form action="{% url 'memo:add_memo' %}" method="POST">{% csrf_token %}
    <table>
      <tr>
        <th>タイトル</th>
        <td>{{ form.title }}</td>
      </tr>
      <tr>
        <th>テキスト</th>
        <td>{{ form.text }}</td>
      </tr>
    </table>
    <button type="submit" class="btn">保存</button>
  </form>

  <div>
    <a href="{% url 'memo:index' %}">ホームへ戻る</a>
  </div>

{% endblock %}

memo/templates/memo/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DjangoBrosMemo</title>
    <link rel="stylesheet" type="text/css" href="{% static 'memo/css/style.css' %}">
</head>
<body>
  <div class="page-header">
    <a style="text-decoration: none;"href="/"><h3>DjangoBrosMemo</h3></a>
  </div>
  <div class="container">
    {% block content %}{% endblock %}
  </div>
</body>
</html>

memo/templates/memo/detail.html
{% extends 'memo/base.html' %}

{% block content %}

  <h2>{{ memo.title }}</h2>
  <div>
    {{ memo.text | linebreaks | urlize }}
  </div>

  <form action="{% url 'memo:del_memo' memo_id=memo.id %}" method="post">{% csrf_token %}
    <button type="submit" class="btn" onclick='return confirm("本当に削除しますか？");'>削除</button>
  </form>

  <button><a class="btn" href="{% url 'memo:mod_memo' memo_id=memo.id%}">編集</a></button>

  <div>
    <a href="{% url 'memo:index' %}">ホームへ戻る</a>
  </div>  

{% endblock %}

memo/templates/memo/index.html
{% extends 'memo/base.html' %}

{% block content %}

  <a class="btn" href="{% url 'memo:add_memo' %}">新規メモ作成</a>

  {% for memo in memos %}
    <a href="{% url 'memo:detail' memo_id=memo.id %}" class="memo-title">
      <div>
        {{ memo }}
        <span class="updated_date">{{ memo.updated_date }}</span>
      </div>
    </a>
  {% endfor %}

{% endblock %}

memo/templates/memo/mod_memo.html
{% extends 'memo/base.html' %}

{% block content %}

  <form action="{% url 'memo:mod_memo' memo_id=memo.id %}" method="post">{% csrf_token %}
    <table>
    <tr>
      <th>タイトル</th>
      <td>{{ form.title }}</td>
    </tr>
    <tr>
      <th>テキスト</th>
      <td>{{ form.text }}</td>
    </tr>
    </table>
    <button type="submit" class="btn">保存</button>
  </form>

  <div>
    <a href="{% url 'memo:detail' memo_id=memo.id %}">戻る</a>
  </div>

{% endblock %}